apiVersion: apps/v1
kind: Deployment
metadata:
  name: p11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p11
  template:
    metadata:
      labels:
        app: p11
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p11
        ports:
        - containerPort: 80
